label day2morning:
    
    #test! i added stuff 
    
    scene bg room with fade
    
    "You wake up bright and early the next day when your cat is kneading your face."
    l "Ow! Stop it, Momo! I’m awake!"
    "Momo" "Meow."
    "You do your usual morning routine, shuffling to the bathroom in a zombie-like fashion. Eventually, you are dressed in your school uniform with ribbons in your hair and a touch of make-up."
    "You look in the mirror and are really feeling the kawaii today. However, you realize that Kaito didn’t show up like he did yesterday morning."
    "Ohayo gozaimasu, Liz-chan! Nothing’s wrong, but uh… Do you have a friend named John?"
    "You can feel your stomach drop and you can’t help but grimace."
    l "Oh gawd… What happened? Did he talk to you?! What did he say?!"
    k "Nothing! Nothing! He was actually hanging around here before I got here."
    l "REALLY!?"
    k "Yeah… He seems really fond of you! He kept talking about how close you two are, how you met, how you laugh at all his jokes, and how you inspired him to get a fedora."
    l "(#justneckbeardthings...)"
    k "He seemed kind of mad at me though… He was also asking what kind of relationship we had and didn’t seem very happy when I said we’d been friends since childhood. Said that he was gonna walk you to school today."
    l "Oh my god…"
    "Kaito laughs lightly. You assume it has something to do with the poorly concealed disgust on your face."
    k "I guess it’s good that I told him I usually walk you to school. He insisted that he wanted to just walk with you, I asked why we couldn’t just walk all together and then he… kind of just ran off?"
    "You sighed with relief."
    l "Thank goodness… Yeah, we’re… kind of friends, but not THAT close. I don’t know, I don’t think he gets it…"
    l "How does he even know where I live?! That’s sooo creepy!"
    k "Hmm… Well, I’m glad I saw him first so I could warn you."
    l "I know, right?! Thank you soooo much for helping me out!"
    k "It’s no problem… If you ever need someone to help you or even protect you, just let me know."
    "He gives you a bright smile highlighted by the morning sunlight. You feel giddy inside."
    l "Thanks… You’re always so reliable.. Kaito-nii-kun!"
    k "Wow, you haven’t called me that in a long time. I think I still like Kaito-kun more, though. And you’ve always been so good to me, too."
    #        >k "Like yesterday! Thanks so much for helping out."
    l "Aw, it’s nothing. Hehe."
    "You two continue on like this as you walk to school together. Maybe it’s just you, but you really enjoyed these little talks you two have together. You’re smiling and jovial the whole time. He seems the same way."
#    "You talk about the upcoming festival, the progress, what happened…"
#        >k "Do you think you can help out again today? Everyone enjoys your help. I think you really impressed everyone last time too."
#            l "Aw, really? Hehe, maybe."
#            "It was nice to assert your territory in front of all those girls."
#            >k "By the way, feel free to come by our class if you ever want to help. We could always use more people, and it'll be fun."
#            l "Hmm, maybe..."
    l "I'll see, but since this is the last day before the festival, hopefully they won't be too busy at my own class."
    l "By the way, I can't wait to hear you sing!"
    k "Eheh, thanks."
    l "Do your classmates even know how amazing your voice is?"
    k "Not at all, actually… I haven’t sung in front of any of them before."
    l "Really?? But I’ve heard you sing… You haven’t even practiced in front of them?"
    k "I haven’t, actually. You’re the only one who’s heard me sing before."
    "Kaito gives you such an affectionate and trusting smile that your cheeks glow pink..."
    k "Anyway, I'm gonna head to class. See you, Liz-chan!"
    l "Bye!"
    "You try to shoo the hearts away floating over your head as you walk to class."
    "That doesn’t last long though because Nick is already there. However, his face is sullen and you can see dark circles under his eyes. He is concentrated on scribbling away some notes in his binder."
    l "Good morning Nick-kun~~~!!!"
    n "...Hey."
    l "What’s wrong? You seem tired."
    n "Hmph… it’s nothing. I’m busy."
    l "With what?? Tell me, hey, tell me~"
    "Leaning over his desk, you take a peak of what he’s working on. Yep, that’s definitely the homework due today."
    "You give him an evil smirk. However, he’s already kind of scooted away from you, looking red. Looks like your chest inadvertently invaded his personal space as well. You can’t tell what he’s more embarrassed about."
    l "Ooooh, you’re a bad student. That’s the English homework due today, huh? Huh!?"
    "S-shut up! Don’t tell me you already did it!"
    "He quickly shuts his binder as you lean in closer to tease him. Just as he does, something else flies out of his binder by accident. It’s a letter."
    "Wait, is that YOUR letter? You recognize the doodle and hearts you had scribbled on it. That was from over a week ago!"
    l "GASP! Was that my letter to you?"
    n "NO!"
    "He quickly swipes it off the ground and shoves it back in his binder. Adamantly, he folds his arms over his now tightly shut binder, with an irritated look on his face, but refuses to look at you."
    n "It was nothing! B-baka!"
    l "Why are you keeping my letters?? Did you like them that much?"
    n "I told you, they’re not!"
    m "hey gaiz wats happenin"
    "You turn and see Myca settling in at her desk. She looks short as usual. You quickly rush to her and speak in a poorly concealed hushed voice."
    l "Oh my gosh…! There’s so much I have to tell you…!"
    m "Really? More stuff happened since we talked last night? And what’s Nick’s problem?"
    l "Apparently, he’s still holding onto the love letter I gave him last week! AND! AND!"
    l "John knows where I live!! He was HANGING AROUND my house this morning!"
    m "Uh, don’t break my desk… That’s totally creepy though! How would he have even gotten it!"
    l "I don’t know… I bet he asked around. Maybe he asked my cousin or something. Ew!"
    m "Well, did you see him? What’d he do??"
    l "Actually, since Kaito is usually there first, he actually ran off! Ugh, I’m so thankful Kaito-kun was there!"
    m "Hah! Did he really just run away like that? Your harem is defending you! Lucky."
    l "H-hey, they’re not my harem!"
    m "Speaking of such, what were you saying about Nick?"
    l "Dude, just earlier he accidentally showed that he STILL holds onto the stuff I gave him…"
    m "EhhH!!! USO!!"
        #    >m "So not only did he spend all that time with you yesterday and say that weird stuff about not responding to your confession yet…"
         #   m "He also kept all your love letters?!"
    m "Who does all that!? He obviously still likes you! It’s even more obvious now!"
    "Before you could damage her desk even more in excitement, you hear the school bell ring. You rush to your seats as the teacher comes in just on time."
    "You’re excited to gossip more during lunch, so you have a hard time paying attention during class. Actually, the more you think about, the more you realize just how close the festival is!"
    "Today would be the last day to work on the preparations… Then tomorrow-- tomorrow!-- would be when the festival officially starts. Does she really have to find a dance partner by then?"
    "When the lunch bell rings, you ambush Myca’s desk."
    l "Ahh, I can barely concentrate! Are you serious about this bet thing!? Do you really think I have a chance with EITHER of them!?"
    m "Yes and yes! And apparently John knows where you live too! Maybe he’s planning the wedding already in his head! Hahaha!"
    l "Don’t say that!! Ughh! And where are you going!?"
    m "Oh, I forgot to mention I gotta go do some last minute Anime Club stuff for lunch. I mean, we’re mostly done but something came up."
    l "Ehhh!? You’re leaving me?!"
    "Myca pats your shoulder."
    m "You’ll be fiiine~ I mean, unless you wanna come with, but uh, I doubt that."
    "You suddenly flash to the last Anime Club meeting where everyone was having pretend ninja fights."
    l "Err… I’ll figure something out."
    m "Okay, bye!"
    "You stare at your lunch blankly and bite your lip. There’s no way you can eat alone, especially with all these thoughts stressing you out. You decide to…"
      
    
    return