label day2decision1_gotoanimeclubanyway:
    
    scene bg room with fade

    "You don’t like sitting alone like this, so your impulse is just to get up and follow Myca. Maybe you can talk to her when she is done and just eat in the clubroom until then?"
    "You make your way to the clubroom hall, blending in along with all the bustling traffic in the hallway. It really was lively, with the festival tomorrow…"
    "You’re actually not sure what the Anime Club is planning. Actually, the closer you get the clubroom, the more you feel your stomach drop."
    "Maybe this wasn’t such a good idea…"
    "But you don’t want to look stupid, walking this far and turning around."
    "With a shaking hand, you slide open the club door…"
    "Immediately magical girl music is blasting in the background."
    m "Everyone, sign in please!"
    "Myca is at the front while several students are in different spots in the classroom, talking loudly or drawing."
    "Some of them are debating about power levels, others are comparing drawings of some lewd boy on boy action. A girl and her friend are dancing in corner to the music with idol-like grace."
    " A goth looking girl sighs angrily. An overweight guy pushes up his glasses and is yelling his waifus name as he reads his manga. Another girl openly picks at the pimples on her legs"
    "You sit near the back and try not to make eye contact with any of them."
    "Myca starts the meeting. You zone out and start checking your phone while you munch on your bento."
    "Some part of you vaguely hopes that maybe Nick or Kaito will pop in for some god unknown reason, but they don’t."
    "Myca seems done talking about whatever she was talking about puts some anime episode on."
    "The students either watch or are move to talk to their friends. Myca is busy talking to another classmate, but a few familiar people approach."
    "Rhiannan" "HEY LIZ" with vpunch
    "She jumps up from behind you and you resist the urge to self-defensively punch her. Rhiannan is wearing a Konoha Naruto symbol on its head and has a fake kunai strapped to her waist. You wonder why it hasn’t been confiscated yet."
    "Rhiannan" "You’re usually not here!!! Are you going to join us for our ANIME COSPLAY CAFE?"
    l "Oh, uhh, no, probably just gonna stick with my class."
    "Rhiannan" "Aww, that’s too bad! You could have dressed up as Sakuhana-chan, my original character. You look just like her!"
    "She whips out her sketchbook of crudely drawn anime characters. There’s one that (sort of?) has pigtails."
    l "...Yeaah. It’s a shame."
    "Rhiannan" "Well, if you ever reconsider you can go on my deviantart to look at my art!"
    l "Sure… Uh, why are you dressed like that? ...Are you allowed to bring that to class?"
    "You motion at the plastic kunai and Rhiannan jumps into a defensive stance, wielding it. You instinctively move away in your seat."
    "Rhiannan" "No, but they can’t have it! It cost $20 and I need it for my cosplay!"
    "She proudly does an awkward kick in the air in front you."
    "Rhiannan" "I’m in my SASUKE mode, you know?!"
    "Rhiannan" "From Naruto."
    l "Ah… yes."
    "Rhiannan" "Great! I’m glad you recognize me! OH, I just thought of this great move I could do, I gotta go tell Kristen…"
    "Rhiannan" "JA NE, LIZ-SAN."
    "She rushes off to wherever. You just sigh to yourself, happy she’s gone."
    "Myca appears and sits down next to you."
    m "Hey, I thought you didn’t want to come today."
    l "({i}I don’t, but…{/i})"
    l "Eh, I didn’t have anything else to do."
    m "Oh okay. I’m, uh, surprised you wanted to come at all. "
    m "You looked like you wanna to choke Rhiannan back there."
    l "I DID, but tell her I said that." with vpunch
    m "I’m guessing you’re not joining us in our HARE HARE YUUKAI dance practice later?"
    l "Yeaaah, nope."
    "Myca just laughs. She knows you like anime, but not THIS much like most of the people here."
    m "Well, I’ve gotta go collect some surveys now. Hope you, uh, enjoy yourself. See you back in class."
    "You wave as she scurries off, and go back to picking at your bento."
    "Maybe it wasn’t such a good idea afterall…"
    "???" "Hey Liz~"
    "You turn and see Fiona, one of the normal anime fans here who is pretty down to earth and cute looking. "
    l "Hey!! Nice seeing you."
    "Fiona" "Same! Hey, this John guy was looking for you earlier."
    "Immediately you feel your heart drop. Before you can hide, Fiona is waving someone over happily."
    "And there he is… John-kun. He is looking blobby as ever and jiggles with excitement as you lock eyes from across the room."
    "He downs his drink as the anime music booms."
    "Fiona" "What’s wrong? You look sick."
    l "({i}Yeah, I’m trying not to vomit…{/i})"
    l "Uhh, it’s nothing… eheh."
    "Fiona" "Oh, alright then. I gotta go, I think Bobby is calling me…"
    "You reach out feebly as you watch her go… Now there’s no escape."
    j "LIZZY-CHAN~" with vpunch
    "You burry your head into your hands, accepting your fate. "
    "John has made his way to you, his eyes sparkling with adoration. He sits next to you. "
    l "Hey… "
    j "What’s wrong? You look upset!"
    l "I just… have a stomachache."
    j "Oh no!! Here, let me show you something funny to cheer you up. Can you guess?"
    "You just stare at him with dead, blank eyes instead of continuing the conversation."
    j "Err… it’s my Chewbacca impression! You said you love my Chewbacca impression!"
    l "I… I did?"
    j "Yeah! Ok, I’m gonna start…"
    j "Ahem…"
    j "...URUURRHHHH." with vpunch

    #maybe add SOUND EFFECTS HERE HAHAHAH
    
    j ".......UUURUUUURUHHR." with vpunch
    l "({i}God, please kill me.{/i})"
    "..."
    "The rest of lunch goes on like this. You listen in broken silence as John continues to make noises at you."
    "Ten minutes before lunch ends, you stand up suddenly and excuse yourself because \"Class is starting soon!\""
    "John watches you leave sadly. Meanwhile, you nearly sprint out of the clubroom."

    return