label day2decision2_helpkaitoout:
    
    scene bg room with fade
    
    "Since it’s going to be the busiest day, you figure Kaito would appreciate the help."
    "Besides, you’d love to hear more of his singing…"
    "You join the crowd in the hallway, happily walking up the stairs to the upperclassmen rooms."
    "You slide the door open and are greeted with familiar faces."
    "Maybe you’re better off as a senpai…"
    k "Hey! You came!"
    "Kaito rushes over to you, clearly happy at your presence."
    l "Of course!!"
    k "We were just about to head out to the gym for rehearsal and setup."
    k "Can you help carry some stuff? It’s fine if it’s too heavy."
    l "Oh, I’ll be fine."
    "You casually pick up a 2 boxes full of clothing and props and shoulder a trunk with instruments in it."
    "The students are gawking at you…"
    "You can’t help but feel a little smug. You bet they don’t even lift."
    k "Jeez Liz-chan… I forget you’re so strong sometimes!"
    l "Oh, this? I guess a little!"
    "..."
    "You and Kaito head out first and make your way to the gym."
    "With the help of other classmates, you guys set up chairs and move props and instruments backstage."
    l "Nee, Kaito-senpai, are you going to be playing an instrument too or just the piano?"
    k "Actually, I’ll be playing the piano while singing."
    l "GASP! No way!"
    l "That’s so cool!! You can sing AND play the piano!"
    k "Heh… Not as cool as you though, with your cooking and sewing skills!"
    l "({i}Ooooh~ Still hungry~ {/i})"
    k "Not to mention super strength…"
    l "({i}I’m full~{/i})"
    k "Anyway, I think we’ve helped out back here as much as we could."
    k "They have a piano backstage, but umm…"
    k "...I’m gonna practice in the music room. It’s too embarrassing to practice in front of everyone..."
    l "Aw, really? Don’t you think you should make sure your setup is fine for tomorrow?"
    k "Eh, I’m not really worried. I’m sure it’s fine."
    k "But, umm… Did you want to come with me?"
    l "I-I thought you said it was too embarrassing in front of other people…"
#    k "Well, you’re not just anyone, you’re my closest friend…"
#    if kaito_lunch then
#            k "And like I said at lunch, I don’t mind if it’s you."
#   else
#           k "Of course I don’t mind if it’s you…"
    l "O-okay…!"
    "Walking together, you both head out of the building to the other with the music room."
    "As you two chat happily about the festival, you notice the sun is setting already."
    "You’re reminded of the bet, and how you want to ask either Nick or Kaito of the dance…"
    "There’s not much time left. You wonder if Kaito would say yes…"
    "But when you look up at Kaito’s warm smile in the setting sun, you can’t help but get all choked up and embarrassed!"
    "By the time you reach the music room, Kaito must see the conflict on your face."
    k "Is something the matter?"
    l "N-no! Nothing!"
    k "Okay, then. I’m gonna go ahead and practice."
    l "Go ahead!"
    "You plop down in the chair, excited to hear his voice."
    "He sits down in the piano chair, looking back at you with a sheepish smile."
    "And then he starts to play..."
    "..."
    "His fingers run delicately up and down the keys, making the piano play a bitter sweet melody..."
    "And his voice is so deep and emotional..."
    "You can't help but sigh with content."
    "He stops and turns back to you."
    k "Does it sound good so far to you?"
    l "Absolutely!"
    l "I love this song so much too!"
    k "Really? I'm glad."
    l "I wish I had even a bit of your musical talent."
    l "Well, I can play a mean recorder if I do say so myself..."
    "Kaito laughs, amused. "
    k "You can play your recorder if you want for our talent show..." 
    l "W-what? No way... They wouldn't appreciate my skills."
    l "Besides, it's nothing like your piano skills..."
    k "Well, it's actually a pretty simple piece."
    k "I could teach you if you'd like."
    l "Really??? If you don't mind!"
    k "Yeah! It'll be fun. Maybe you can accompany my singing."
    l "Yeahhh, I don't know about that."
    "Kaito just chuckles and scoots over, patting the now open seat on the piano bench."
    k "Come sit over here."
    l "Okay…!"
    "You make yourself comfortable on the seat. You also become keenly aware of how close your bodies are."
    k "It’s like this…"
    "He starts to play the first couple notes notes."
    "Shly, you place your hand up on the keys and follow his lead."
    k "Great! Just like that."
    "You can’t help but glow at his praise."
    l "Yeah!"
    k "Okay this is the next part…"
    "Kaito continues to play the next bit, and you follow along."
    "The sequence of notes starts to get longer and you start to mess up."
    k "It’s alright, it’s a lot to memorize."
    k "You’ve almost got it though!"
    l "It’s hard now though…"
    k "It’d help to get the finger placement correct like I do…"
    l "I caaan’t, my fingers automatically go like this…"
    k "Here, let me show you…"
    "Kaito gets up and walks over to your side. He repeats the part with nimble fingers."
    "You copy him again, but inevitably stumble."
    l "Your hands are just so much bigger…"
    k "No, really, it’s simple! Here…"
    "His fingers touch yours. You freeze in place as he holds your hand, showing you the order."
    "Suddenly, you’re not paying attention. All you can think about his hand in yours."
    "He’s also behind you, leaning forward…"
    "You can feel his soft hair brushing against your cheek. He’s saying something, but it’s just so distracting..."
    k "...thumb goes over here. See?"
    l "W-what? I mean, yes."
    k "Alright, you try it now..."
    "Mechanically, your fingers move in the motion that Kaito taught you."
    k "There you go! Together now…"
    "Kaito is still standing and leaning over you, his face still inches from yours…"
    "He starts to play and you hurry and keep up with him. You manage to pull it off."
    l "...I DID IT!"
    k "You did! Okay, watch this..."
    "Kaito leaves your side unfortunately. He sits back down at his seat."
    k "Follow my lead."
    "He starts to play the harmony of the song and you join in on the melody you just learned."
    "Together, you two make beautiful music..."
    "When the song finishes, you two beam at each other, laughing happily."
    k "Hey…"
    k "This is kind of nice."
    l "What is?"
    k "You know… being close like this."
    l "W-what do you mean?"
    k "The truth is, Liz-chan… Lately, seeing you just as a close friend or sister is…"
    "Kaito’s cheeks are a light shade of red… But, he continues to meet your gaze with determined eyes."
    k "It’s difficult… And… I was wondering if, maybe…"
    "Suddenly, the door slides open! You and Kaito both jump in your seats."
    "Classmate" "Kaito-kuuun, there you are. The teacher needs you."
    l "({i}FFFUCK THIS GUY{/i})"
    k "O-oh… Right now?"
    "Kaito definitely looks disappointed. But he gets up hesitantly."
    "The classmate cock blocker is already on his way out."
    k "I’m gonna head back… Sorry to have to leave you like this."
    k "Just, uh, forget what I was saying… I’ll tell you another time."
    l "Oh, it’s no big deal…!"
    l "Actually… shit, it’s a lot more late than I thought it’d be."
    l "I need to get home before my dad gets mad…"
    k "I’m sorry I can’t walk you home! You’ll be okay?"
    l "Of course I will! Don’t let me keep you! "
    l "Bye Kaito-senpai…!"
    "He says his goodbyes again and waves at you timidly from the door. You wave back and he leaves."
    l "({i}I can’t believe this…!!!{/i}"
    "..."
    "You make it home without incident."
    "The whole way home, your brain is just filled with thoughts of what just happened…"
    "Was that a confession!? Did Kaito really feel the same way you do toward him…!?"
    "Most of all, you didn’t get to ask him anything about the dance!!!"
    "You throw yourself onto your bed when you get home."
    l "SIGH! Oh Momo… I haven’t even asked him to the dance yet!"
    "Momo" "Meow"
    l "I KNOW TOMORROW’S MY LAST CHANCE!"
    l "Guess I’ll have to ask him… or Nick even…"
    "You fall asleep daydreaming about the possibilities…."

    return