label day2decision1_lookfornick:
    
    scene bg room with fade

        #nick is making waffles
    
    "You think about this morning and the way Nick acted… It wouldn’t hurt just to see what he was up to, right? Maybe you could ask him more about it."
    "Regardless, it’s better than just sitting here alone. You turn around in your seat and see that Nick isn’t there."
    "That’s not surprising. Sometimes he’s here, but usually he’ll disappear for lunch."
    "Hmm… Where would a person like Nick head to for lunch?"
    "Probably somewhere pretty empty… So the cafeteria was a no-go, and you’re fairly sure he doesn’t have friends in other classes."
    "You look out the window-- a lot of people are eating outside today since the weather is nice."
    l "({i}Somewhere empty, huh? Guess it wouldn’t hurt to check the roof.{/i})"
    "Students weren’t technically allowed up there, so it was usually empty."
    "You decide to head up there. Even if Nick isn’t there, the nice weather and view wouldn’t hurt."
    "You make your way out of the classroom, where the hallway is bustling. It’s more lively than usual because of the festival."
    "As you climb the staircase to the roof, the number of students starts to thin out and the lunchtime chatter is soon muffled and far away."
    "You open the door and feel a light breeze right away."
    "Shutting the door behind you, you walk forward. You close your eyes and take in the cool wind and smell of waffles."
    "...Wait. Waffles?"
    "You sniff again. Yeah, that’s definitely waffles. Or at least something delicious smelling."
    "???" "...Liz?"
    "You turn to the side and see Nick there."
    l "Oh! I found you!"
    "After a second, you realize Nick has a waffle iron plugged into an outlet while he mixes some batter."
    l "...What the fuck? Are you making waffles?"
    "Nick turns red but tries to play it cool."
    n "Y-yeah. So what?"
    l "Ummm… Cool!"
    "You walk over and sit down next to him against the wall. He’s honestly just squatting down and making waffles."
    l "So… you just felt like making waffles?"
    n "...Yeah."
    l "How’d you even bring a waffle iron in?"
    n "I put it in my bag, duh."
    l "Oh…"
    l "({i}That must be a heavy ass bag…{/i})"
    "After an awkward silence, Nick is the first to speak up."
    n "What are you doing here?"
    l "Hmmm... just thought I’d keep you company up here!"
    "You can’t help your flirtatious tone, especially with the way he squirms. t’s amusing to see him try not to react."
    n "How’d you even know I’d be up here?"
    l "I didn’t! I just kind of guessed. This seems like your kind of place."
    "Nick says nothing. He seems embarrassed but definitely not unhappy."
    l "Did you need any help?"
    n "No, I’m almost done."
    n "..."
    n "...Did you want some?"
    l "Yes!! If you don’t mind…"
    "You watch in adoration as Nick stoically makes waffles."
    l "I didn’t know you could cook so well, Nick-kun!"
    n "Y-you haven’t even tasted it yet."
    "He has a scowl on his face while he tries to focus on pouring the batter into the iron."
    l "({i}Ahhh, I can’t believe I’m gonna taste Nick’s cooking!{/i})"
    n "Jeez, you don’t have to look so happy…"
    l "Ah, sorry, is it obvious?"
    n "Yes…?"
    l "Sorry, I’m just so excited to taste your cooking…"
    l "You’re so good at everything! You can build things and cook! Wow!"
    l "You’ll make a great wife someday."
    n "H-hey…"
    l "Just kidding!"
    "Nick scoffs at you, but his cheeks are red. "
    "While you two chat, the waffles are done at some point."
    "Nick takes out plastic plates, knives, forks, butter, syrup, and napkins."
    l "W-wow… Your bag can hold a lot."
    "He just shrugs. He cuts a slice of the waffle but seems to hesitate for a brief moment."
    "Before you can think about it, he offers the slice of waffle to you on a fork, close to your mouth."
    n "Try it."
    "Your brain freezes. Is he really offering for you to eat it directly off his fork…?"
    "Sharing food like this… Does he even realize what he’s doing?!"
    "Probably not, so you take advantage and take a bite."
    n "Is it… okay?"
    l "MMMMM! WOW!"
    "You swallow happily. Truthfully, it tasted like a waffle should, but you’re so happy it taste extra good."
    l "It’s great!! You’re an amazing cook!"
    n "You’re exaggerating…"
    "Despite his words, he definitely looks happy. He takes a bite himself from the same fork."
    n "I guess it’s pretty good…"
    l "Nick-kun… we used the same fork…!"
    n "???"
    n "So wha… ?!"
    "Nick turns bright red."
    l "It’s an… an…"
    l "INDIRECT KISS!!" with vpunch
    n "Huh!? That doesn’t count!"
    l "Do it again!" with vpunch
    n "No way!" with vpunch
    "With hearts in your eyes, you try to grab the fork out of his hand and he pulls away."
    "You two play fight for a bit, then eventually settle down and eat."
    "Under the blue sky and light sky, you and Nick eat waffles together and chat lightly."
    "After a while, you two sit in a surprisingly comfortable silence."
    n "...Mm, I think the lunch bell is going to ring soon…"
    l "Awww~ This was so fun though!"
    n "Yeah…"
    n "...Um."
    l "?"
    n "Thanks for… hanging out with me."
    "You feel your heart seize up at his timid smile.
    l "({i}HNNNNGGG…{/i})"
    n "Also… that was my first indirect kiss you know."
    l "Huh?!"
    n "I guess I don’t mind if it’s you."
    l "?!?!?!"
    "You gasp loudly, completely red in the face."
    "Before you have time to say anything, he hurries off to class (with all his waffle stuff packed)."
    l "Nick-kun…"
                   

    return