label day3morning:
    
    scene bg room with fade
    
    "Sunlight filters into your room from the windows, giving the room a gentle morning glow…"
    "You turn over and dig deeper into your blankets to avoid it."
    "Then your three alarms start to go off in succession."
    l "UUUGHH!!" with vpunch
    l "IT’S THE WEEKEND, MAKE IT STOP!!" with vpunch
    "Diana" "Uhh, don’t you have that festival today?"
    l "GASP! I DO!"
    l "I think that’s why I set those alarms…"
    l "Also, I had this nightmare that Nick and Kaito were fighting over me…"
    l "And I cried out for them to stop and so they both agreed to share me…"
    "Diana" "Really? That’s a nightmare?"
    l "Why are you here instead of Kaito-senpai?"
    "Diana" "I dunno, maybe because you guys have that festival and he’s over there?"
    l "That’s true."
    "You roll out of bed and lay there for a while."
    "Eventually, you make it to the bathroom and freshen yourself up."
    l "Ohhh, I should look good today…"
    "You dig through the closet for an outfit… Pearls, polka dots, bright colors…"
    "After careful selection and nimble make-up, you look in the mirror and see a hot chick."
    "It’s you!"
    l "Alright… TODAY’S THE DAY!" with vpunch
    l "I’M GONNA ASK A BOY OUT!" with vpunch
    "..."
    "When you reach the school gate, Myca is already there, waiting for you."
    m "Hello, my tomodachi"
    l "Hello to you too!"
    m "So you have a date tonight with John, right?"
    l "W-WHAT!? NO!" with vpunch
    m "Then with who?"
    l "I… I haven’t asked him yet."
    m "Ask who?"
    l "I’m not telling… "
    m "So you don’t know yet."
    l "Whaaaat, noo…"
    l "({i}Yes…{/i})"
    l "Myca, this is a time for fun! Let’s get going at look at the booths!"
    m "True, our shifts for the haunted house is later."
    m "Where do you wanna go first?"
    l "Let’s just walk through…"
    "You two head into the school, which is decorated in colorful banners and signs."
    "It’s not too crowded yet since it’s the morning, but the atmosphere is buzzing full of excited chatter."
    "Bao" "Hey Liz! Myca!"
    m "Hey."
    l "Hi Bao! Um… what are you doing?"
    "Bao" "It’s a kissing booth for our club!!! Free kisses for a dollar!"
    l "So it’s not even free then…"
    m "And it looks pretty empty…"
    "Bao" "That’s just because it’s the morning."
    "Bao" "The ladies will come. Especially when they see… these."
    "Bao flexes and a little muscle comes out."
    "You and Myca stare blankly."
    m "Well, good luck with that."
    l "We’re gonna go now."
    "Bao" "O-okay! Tell people about us, okay?!"
    l "Sure!"
    "You two continue to make your way down the aisle of booths."
    "You end buying crepes because they’re fucking crepes and who says no to crepes?"
    "Later, you pass by one of the classrooms that seem to be doing some sort of cafe."
    "You spot a good friend, Danita!"
    l "GASP! You look so good in that outfit!"
    "Danita" "Thanks."
    m "So, what kind of cafe is this?"
    "Danita" "A tsundere cafe. I get to be an asshole to customers they like it."
    "Danita" "Great, isn’t it?"
    m "I think you’re forgetting the -dere part…"
    "Danita" "Pfffttt, look at the line, they don’t mind."
    l "Whoa… You’re right."
    "Danita" "Anyway, we’re doing a play later, here’s a flier!"
    "The three of you talk a bit more before saying goodbyes."
    "Later, you and Myca buy more food like cupcakes and yakitori, munching as you look around."
    "Fiona" "Hey guys!"
    m "Hey!"
    "You see your good friends Fiona and Cynthia hovering near the entrance of another classroom."
    l "Hey! What’s this booth?"
    "Cynthia" "Our club is doing an art exhibit! Wanna see? Only a dollar entry."
    l "Sure!"
    "You make your way in and check out the art that they did."
    "And it’s all… boys fucking. Or kissing. Or hugging."
    l "Wow, that’s… Um… Interesting! You guys drew this?"
    "Fiona" "Yep! I call this piece… \"Yami Yugi As A Cat Boy.\""
    "Cynthia" "And this is called \"Forbidden Love: Roxas and Axel.\""
    l "Well… it’s really well drawn!"
    "Cynthia" "Thanks, Liz!"
    "Fiona" "Yeah!"
    "After some small talk, you and Myca head out together."
    l "Well, that was… weird. "
    l "...Is your nosebleeding, Myca?"
    m "N-NO! That art was definitely just weird and not sexy or anything…!"
    "You make your way to the next classroom and just gets fucking weirder."
    l "Does that say \"The Furry Cafe\"?"
    m "I think it does… That’s… interesting."
    "A guy dressed as an otter steps out, holding fliers."
    "Luke" "Hey."
    l "Oh! Is that you, Luke? I didn’t, uhhh, recognize you."
    "Luke" "Of course not… I’m currently my fursona."
    m "Your what?"
    "Luke" "My FURSONA? The ME in another life?"
    "Luke" "Ugh, you cis scum just don’t understand!"
    l "Um... Aren’t you also cis?"
    "Luke" "I’m not cisgendered, I’m OTHERKIN!"
    "Luke" "And it’s not he/him/himself, please refer to me as paw/paws/pawself! UGH!"
    "Luke turns away and heads back into his Furry Cafe, grumbling, his otter tail swishing in the air."
    m "Jeez… Imagine if I had dated that guy."
    l "Right!?"
    "..."
    "It’s well into the afternoon and the festival definitely has become a lot more lively."
    "You pass by other classes, such as seeing Herbie and his asian crew do breakdancing, Blackwelder shut down some innocent students selling food, Stacey hosting a video game tournament…"
    m "Hey, my shift for Anime Club is coming up, so I’m gonna start heading back."
    "You finish munching on your spam musubi before responding."
    l "Alright. I can come with you."
    "When you and Myca approach the Anime Clubroom, you can see it’s decked out with all sorts of anime signs and posters, advertising its Cosplay Cafe."
    "There sure is a lot of Cafes this year…"
    "As you step in, you see that basically everyone is cosplaying. Some good, some bad, some really bad…"
    "Rhiannan" "HEY LIZ" with vpunch
    l "?!?!" with vpunch
    l "O-oh hey."
    "Rhiannan" "Do you like my outfit?!"
    l "Umm… yeah."
    "Rhiannan" "I’m Ed from Fullmetal Alchemist!"
    "She starts doing some awkward combat moves."
    l "Cooool."
    l "({i}Why is she talking to me.{/i})"
    m "Hey, I’m gonna take up my shift. You can go now, Rhiannan."
    "Rhiannan" "Aww, but I was having so much fun!"
    "Rhiannan" "WRYYYYYY! LOL! XD"
    l "Yeah, I’m gonna go now, Myca."
    m "See ya!"
    "After making it very clear to Rhiannan you were going different directions, you step out of the hallway…"
    "As you look around, you realize all that was left now is checking out Kaito or Nick’s booth…"
    "The sun is already setting. You’re not sure you’ll have time for both."
    "It’s time to decide..!"
    "So it’s either the haunted house where, Nick is at, or the talent show in the show, where Kaito is…"
    "You wonder if you’ll finally muster the courage to ask one of them at their booth or end up alone with… John."
    "Where should you go?"

    return